### PR TITLE
Vulkan

### PR DESCRIPTION
**Pull request by rpavlik**
@oddhack I've started this for Vulkan for you - in case you wanted to make the XML alignment automatically.

### CODE REVIEW

**Comment by oddhack** [comment]
I know basically nothing about C# or its ecosystem so my ability to run it is effectively zero, alas. Is it Windows-specific?

**Comment by rpavlik** [comment]
Nope, it works on Linux just fine. I actually wrote it entirely on Linux. I can improve the getting started docs, the tldr is: https://dotnet.microsoft.com/download for the .net 5 sdk, then open it in Visual Studio Code for a nice editor, or see the readme for the commands to build and run. (The code itself is well documented, just not the getting started) C# is similar enough to C++ or Java for most purposes. The only bits I haven't done too much of are the "policy" parts of how you like things formatted in Vulkan or other standards.

I tried doing this in Python first, but found it was really hard to customize how xml was being serialized, unfortunately.

**Comment by rpavlik** [comment]
Did some cleanup. The logic to customize begins here: https://github.com/rpavlik/PrettyRegistryXml/pull/7/files#diff-a35de157d4660d42c4d93760d58c7049f15fe458af66664856f9b7d79c2eca80R139

**Comment by rpavlik** [comment]
Actually I think I mightjust merge this one so if you feel like trying it, you have some CI-made builds of it, etc.

**Comment by rpavlik** [comment]
@oddhack  there, now you have pre-built Linux binaries here: https://github.com/rpavlik/PrettyRegistryXml/releases/tag/v2.3.0

**Pull request merged**
